venv13/belavia/accounts/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('main/', views.main, name='main'),
    path('history/', views.history, name='history'),
    path('fleet/', views.fleet, name='fleet'),
    path('base/', views.base, name='base'),
    path('base1/', views.base1, name='base1'),
    path('base3/', views.base3, name='base3'),
    path('base4/', views.base4, name='base4'),
    path('base5/', views.base5, name='base5'),
    path('base6/', views.base6, name='base6'),
    path('schedule/', views.schedule, name='schedule'),
]

venv13/belavia/belavia/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from belavia import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout.html/', auth_views.LogoutView.as_view(), name='logout.html'),
    path('flights/', include('flights.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

venv13/belavia/flights/urls.py
from django.urls import path
from . import views

app_name = 'flights'

urlpatterns = [
    path('search/', views.search_flights, name='search_flights'),
]

venv13/belavia/accounts/models.py
from django.db import models

# Create your models here.

venv13/belavia/flights/models.py
from django.db import models

class Flight(models.Model):
    departure_city = models.CharField(max_length=100)
    arrival_city = models.CharField(max_length=100)
    departure_time = models.DateTimeField()
    arrival_time = models.DateTimeField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.departure_city} → {self.arrival_city} ({self.departure_time})"

class Booking(models.Model):
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    booked_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} — {self.flight}"

venv13/belavia/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

venv13/belavia/flights/forms.py
from django import forms
from .models import Booking


class FlightSearchForm(forms.Form):
    departure_city = forms.CharField(max_length=100)
    arrival_city = forms.CharField(max_length=100)


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['full_name', 'email']

venv13/belavia/accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView
from .forms import UserRegistrationForm
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('profile')
        else:
            return render(request, 'accounts/register.html', {'form': form, 'errors': form.errors})
    else:
        form = UserRegistrationForm()

    return render(request, 'accounts/register.html', {'form': form})





@login_required
def profile(request):
    return render(request, 'accounts/profile.html', {'user': request.user})


def logout(request):
    return render(request, 'accounts/logout.html')


class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'

def main(request):
    return render(request, 'accounts/main.html')

def history(request):
    return render(request, 'accounts/history.html')

def fleet(request):
    return render(request, 'accounts/Fleet.html')
def base(request):
    return render(request, 'accounts/base.html')
def base1(request):
    return render(request, 'accounts/base1.html')
def base3(request):
    return render(request, 'accounts/base3.html')
def base4(request):
    return render(request, 'accounts/base4.html')
def base5(request):
    return render(request, 'accounts/base5.html')
def base6(request):
    return render(request, 'accounts/base6.html')
def schedule(request):
    return render(request, 'accounts/schedule.html')

venv13/belavia/flights/views.py
from django.shortcuts import render
from .models import Flight
from .forms import FlightSearchForm
from .forms import BookingForm

def search_flights(request):
    form = FlightSearchForm(request.GET or None)
    flights = None
    if form.is_valid():
        flights = Flight.objects.filter(
            departure_city__icontains=form.cleaned_data['departure_city'],
            arrival_city__icontains=form.cleaned_data['arrival_city']
        )
    return render(request, 'flights/search.html', {'form': form, 'flights': flights})



def book_flight(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.flight = flight
            booking.save()
            return render(request, 'flights/confirmation.html', {'booking': booking})
    else:
        form = BookingForm()
    return render(request, 'flights/book.html', {'form': form, 'flight': flight})

venv13/belavia/accounts/templates/accounts/Fleet.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/demo.css' %}">
<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
<link rel="stylesheet" href="{% static 'css/kaiadmin.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Флот{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        body {
            background-color: #77bcf1;

        }

        .container {
            text-align: center;
            border: 2px solid black;
            border-radius: 20px;
            background: #fff;
            margin: 20px auto;
            max-width: 1200px;
            padding: 20px;
            box-shadow: 10px 10px 10px black;
        }
        .post img {
            max-width: 100%;
            border-radius: 10px;
        }
    </style>
    {% block extra_head %}{% endblock %}

</head>
<body>
    <div class="container">
<h1>Наш флот:</h1>
        <br>
<h1>Boeing 737-300</h1>
<img src="{% static 'img/733.jpg' %}" alt="733">
<h1> 2 самолета: EW-366PA и EW-254PA</h1>
<p>ICAO code: B733<br>
завод-изготовитель: United States, Renton<br>
Длина: 33,4 м<br>
Размах крыла: 28,9 м<br>
Высота: 11,1 м<br>
Макс. взлетный вес: 56 470 кг<br>
Крейсерская скорость: 780–793 км/ч (Mach 0,74)<br>
Дальность полета: 4 200 – 4 600 км (зависит от нагрузки и конфигурации)<br>
Потолок высоты: 11 300 м (37 000 футов)<br>
Возраст ~29.6 лет<br>
*на фотке изображен Boeing 737-300 EW-254PA<br>
*Boeing 737-300 EW-366PA временно не эксплуатируется</p><br>





<h1>Boeing 737-800</h1>
<img src="{% static 'img/738.jpg' %}" alt="738">
<h1> 5 самолетов: EW-455PA, EW-456PA, EW-457PA, EW-527PA, EW-544PA</h1>
<p>ICAO code: B738<br>
завод-изготовитель: United States, Renton<br>
Длина: 39,5 m<br>
Размах крыла: 35,7 m<br>
Высота: 12,5 m<br>
Максимальный вес при взлете: 79000 кг<br>
Крейсерская скорость: 842 км/ч (Mach 0,79) <br>
Дальность полета: 5 769 km<br>
Потолок высоты: 41 000 ft (12 500 m)<br>
Емкость топливного бака (крыло+фюзеляж): 7,8 t + 13,1 t<br>
Возраст ~11.5 лет<br>
*на фотке изображен Boeing 737-800 EW-456PA<br><br></p>





<h1>Boeing 737 MAX 8</h1>
<img src="{% static 'img/38.jpg' %}" alt="38">
<h1>1 самолет: EW-528PA</h1>
<p>ICAO code: B38M<br>
завод-изготовитель: United States, Renton<br>
Длина: 39,5 m<br>
Размах крыла: 35,9 m<br>
Высота: 12,3 m<br>
Максимальный вес при взлете: 82190 кг<br>
Крейсерская скорость: 842 км/ч (Mach 0,79) <br>
Дальность полета: 6 570 km<br>
Потолок высоты: 41 000 ft (12 500 m)<br>
Емкость топливного бака (крыло+фюзеляж): 7,8 t + 13,1 t<br>
Возраст ~6.5 лет<br>
*на фотке изображен Boeing 737 MAX 8 EW-528PA<br>
*Boeing 737 MAX 8 EW-528PA временно не эксплуатируется<br><br></p>




<h1>Embraer 175LR</h1>
<img src="{% static 'img/E75L.jpg' %}" alt="75">
<h1>1 самолет: EW-512PO</h1>
<p>ICAO code: E75L<br>
завод-изготовитель: Brazil, São José dos Campos<br>
Длина: 31,68 m<br>
Размах крыла: 26 m<br>
Высота: 9,86 m<br>
Максимальный вес при взлете: 38800 кг<br>
Крейсерская скорость: 850 км/ч (Mach 0,79) <br>
Дальность полета: 3 500 km<br>
Потолок высоты: 41 000 ft (12 500 m)<br>
Емкость топливного бака (крыло+фюзеляж): 9,5 t<br>
Возраст ~7.2 лет<br>
*на фотке изображен Embraer 175 EW-512PO<br></p><br>




<h1>Embraer 195LR</h1>
<img src="{% static 'img/E195.jpg' %}" alt="195">
<h1>4 самолета: EW-399PO, EW-400PO, EW-513PO, EW-514PO</h1>
<p>ICAO code: E195<br>
завод-изготовитель: Brazil, São José dos Campos<br>
Длина: 38,65 m<br>
Размах крыла: 28,72 m<br>
Высота: 10,55 m<br>
Максимальный вес при взлете: 52290 кг<br>
Крейсерская скорость: 870 км/ч (Mach 0,80) <br>
Дальность полета: 4 815 km<br>
Потолок высоты: 41 000 ft (12 500 m)<br>
Емкость топливного бака (крыло+фюзеляж): 16.3 t<br>
Возраст ~9,125 лет<br>
*на фотке изображен Embraer 195 EW-400PO<br></p><br>




<h1>Airbus A330-243</h1>
<img src="{% static 'img/a332.jpg' %}" alt="332">
<h1>3 самолета: EW-587PD, EW-588PD, EW-589PD</h1>
<p>ICAO code: a332<br>
завод-изготовитель: France, Toulouse (TLS)<br>
Длина: 58,82 m<br>
Размах крыла: 60,3 m<br>
Высота: 17,39 m<br>
Максимальный вес при взлете: 242000 кг<br>
Крейсерская скорость: 870 км/ч (Mach 0,80) <br>
Дальность полета: 12 000 km<br>
Потолок высоты: 42 650 ft (13 000 m)<br>
Емкость топливного бака (крыло+фюзеляж): 109.185 t<br>
Возраст ~22,5 лет<br>
*на фотке изображен Airbus A330-243 EW-588PD<br></p>
        {% block content %}{% endblock %}

    <br><button class="btn btn-secondary"><a href="{% url 'main' %}">На главную</a></button>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_js %}{% endblock %}

</body>
</html>

venv13/belavia/accounts/templates/accounts/base3.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/demo.css' %}">
<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
<link rel="stylesheet" href="{% static 'css/kaiadmin.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Расписание{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        body {
            background-color: #77bcf1;

        }

        .container {
            text-align: center;
            border: 2px solid black;
            border-radius: 20px;
            background: #fff;
            margin: 20px auto;
            max-width: 1200px;
            padding: 20px;
            box-shadow: 10px 10px 10px black;
        }
        .post img {
            max-width: 100%;
            border-radius: 10px;
        }
    </style>
    {% block extra_head %}{% endblock %}

</head>
<body>
 <div class="container">

<table class="table flights fl-arrival">
        <thead>
        <tr>
            <th class="airline_logo">Авиакомпания</th>
            <th class="flight_number">Рейс</th>
            <th class="airport_name">Прибывает из</th>
            <th class="airport_sector">Сектор</th>
            <th class="flight_time">Время прилета</th>
        </tr>
        </thead>
        <tbody style="">
        <tr data-href="/raspisanie-rejsov/prilety/2001456231" class="flights-item flights-item--special green">
            <td class="airline_logo"><img src="{% static 'img/Belavia.png' %}" alt="БЕЛАВИА">
            <td class="flight_number">
                <div bis_skin_checked="1">B29308</div>
            </td>
            <td class="airport_name">Шарм-Эль-Шейх</td>
            <td class="airport_sector">4</td>
            <td class="flight_time">
                <time datetime="2025-06-03T00:40:00+03:00">15:00</time>
            </td>
        </tr>
        <tr data-href="/raspisanie-rejsov/vylety/2001455112" class="flights-item flights-item--special">
            <td class="airline_logo"><img src="{% static 'img/Belavia.png' %}" alt="БЕЛАВИА">
            <td class="flight_number">
                <div bis_skin_checked="1">B2988</div>
            </td>
            <td class="airport_name">Москва (Шереметьево)</td>
            <td class="airport_sector">3</td>
            <td class="flight_time">
              <time datetime="2025-06-03T00:25:00+03:00">15:10</time>
            </td>
        </tr>
                <tr data-href="/raspisanie-rejsov/vylety/2001455112" class="flights-item flights-item--special">
            <td class="airline_logo"><img src="{% static 'img/Belavia.png' %}" alt="БЕЛАВИА">
            <td class="flight_number">
                <div bis_skin_checked="1">B2990</div>
            </td>
            <td class="airport_name">С.-Петербург (Пулково)</td>
            <td class="airport_sector">3</td>
            <td class="flight_time">
              <time datetime="2025-06-03T00:25:00+03:00">19:45</time>
            </td>
                </tr>
                </tbody>
    </table>
*Некоторые рейсы могут отличаться от сегодняйшей даты, т.к. это статичное расписание. Расписание на 03.06.2025<br>
        <button class="btn btn-secondary"><a href="{% url 'main' %}">На главную</a></button>


        {% block content %}{% endblock %}
  </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% block extra_js %}{% endblock %}

</body>
</html>

venv13/belavia/accounts/templates/accounts/base4.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/demo.css' %}">
<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
<link rel="stylesheet" href="{% static 'css/kaiadmin.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Расписание{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        body {
            background-color: #77bcf1;

        }

        .container {
            text-align: center;
            border: 2px solid black;
            border-radius: 20px;
            background: #fff;
            margin: 20px auto;
            max-width: 1200px;
            padding: 20px;
            box-shadow: 10px 10px 10px black;
        }
        .post img {
            max-width: 100%;
            border-radius: 10px;
        }
    </style>
    {% block extra_head %}{% endblock %}

</head>
<body>
<div class="container">

    <table class="table flights fl-departure">
        <thead>
        <tr>
            <th class="airline_logo">Авиакомпания</th>
            <th class="flight_number">Рейс</th>
            <th class="airport_name">Направление</th>
            <th class="airport_sector">Стойка регистрации</th>
            <th class="airport_sector">Выход на посадку</th>
            <th class="flight_time">Время вылета</th>
        </tr>
        </thead>
        <tbody style="">
        <tr data-href="/raspisanie-rejsov/vylety/2001455112" class="flights-item flights-item--special">
            <td class="airline_logo"><img src="{% static 'img/Belavia.png' %}" alt="БЕЛАВИА">
            <td class="flight_number">
                <div bis_skin_checked="1">B2989</div>
            </td>
            <td class="airport_name">С.-Петербург (Пулково)</td>
            <td class="airport_sector">1, 2</td>
            <td class="airport_sector">3</td>
            <td class="flight_time">
              <time datetime="2025-06-03T00:25:00+03:00">15:50</time>
            </td>
        </tr>
        <tr data-href="/raspisanie-rejsov/vylety/2001455112" class="flights-item flights-item--special">
            <td class="airline_logo"><img src="{% static 'img/Belavia.png' %}" alt="БЕЛАВИА">
            <td class="flight_number">
                <div bis_skin_checked="1">B29309</div>
            </td>
            <td class="airport_name">Шарм-Эль-Шейх</td>
            <td class="airport_sector">3, 4</td>
            <td class="airport_sector">4</td>
            <td class="flight_time">
              <time datetime="2025-06-03T00:25:00+03:00">16:10</time>
            </td>
        </tr>
                <tr data-href="/raspisanie-rejsov/vylety/2001455112" class="flights-item flights-item--special">
            <td class="airline_logo"><img src="{% static 'img/Belavia.png' %}" alt="БЕЛАВИА">
            <td class="flight_number">
                <div bis_skin_checked="1">B2991</div>
            </td>
            <td class="airport_name">Москва (Шереметьево)</td>
            <td class="airport_sector">1, 2</td>
            <td class="airport_sector">3</td>
            <td class="flight_time">
              <time datetime="2025-06-03T00:25:00+03:00">20:20</time>
            </td>
                </tr>
        </tbody>
    </table>
*Некоторые рейсы могут отличаться от сегодняйшей даты, т.к. это статичное расписание. Расписание на 03.06.2025<br>
        <button class="btn btn-secondary"><a href="{% url 'main' %}">На главную</a></button>


        {% block content %}{% endblock %}
 </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% block extra_js %}{% endblock %}

</body>
</html>

venv13/belavia/accounts/templates/accounts/login1.html
<h1>Вход</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
</form>

venv13/belavia/accounts/templates/accounts/main.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/demo.css' %}">
<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
<link rel="stylesheet" href="{% static 'css/kaiadmin.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Главная{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        body {
            background-color: #77bcf1;

        }

        .container {
            text-align: center;
            border: 2px solid black;
            border-radius: 20px;
            background: #fff;
            margin: 20px auto;
            max-width: 1200px;
            padding: 20px;
            box-shadow: 10px 10px 10px black;
        }
        .post img {
            max-width: 100%;
            border-radius: 10px;
        }
    </style>
    {% block extra_head %}{% endblock %}

</head>
<body>
<div class="container">

    <img src="{% static 'img/Belavia.png' %}" alt="БЕЛАВИА - Авиакомпания Республики Беларусь"> <a
        href="{% url 'profile' %}" class="btn btn-primary btn-round">Profile</a> <a href="{% url 'register' %}"
                                                                                    class="btn btn-primary btn-round">Registration</a>
    <a href="{% url 'flights:search_flights' %}" class="btn btn-primary btn-round">Booking</a> <a
        href="{% url 'history' %}" class="btn btn-primary btn-round">History</a> <a href="{% url 'fleet' %}"
                                                                                    class="btn btn-primary btn-round">Our
    fleet</a> <a href="{% url 'schedule' %}" class="btn btn-primary btn-round">Табло вылета/прилета</a>

    <main>
        <br><br>
        <h1>Основным хабом авиакомпании «Белавиа» является Национальный аэропорт Минск</h1>
        <img src="{% static 'img/UMMS.webp' %}" alt="Minsk-2"><br><br>
        <h5>Национальный аэропорт «Минск» (бел. Нацыянальны аэрапорт «Мінск») — главный международный аэропорт в
            Беларуси. Находится в 21 км (по шоссе — 41 км) от центра Минска. Создан 1 июля 1983 года как Второй Минский
            объединённый авиаотряд.</h5><br><br>
        <h1>Новая эра</h1>
        <img src="{% static 'img/a332.jpg' %}" alt="332">
        <br><br>
        <h5>🙌✈️Новая эра: теперь во флоте «Белавиа» есть абсолютно новый для белорусской авиации тип воздушных судов —
            Airbus A330-200!

            Что это значит для авиакомпании?
            Возможность совершать дальнемагистральные рейсы и открывать новые маршруты. Знаем: этого ждут многие!

            И, конечно, мы очень много готовились:<br>
            ➡️Усиленно учились. Причем все: пилоты, техники, бортпроводники и сотни коллег из других подразделений.<br>
            ➡️Отточили навыки на практике. Не только в Беларуси, но и за рубежом!<br>
            ➡️Настроили новые процессы технического обслуживания новых самолетов, загрузки багажа, обслуживания на борту
        </h5>
        <br><br>
        <h1>Кратко об «Белавиа»</h1>
        <h5>«Белавиа» (бел. Белавія) — белорусская государственная авиакомпания со штаб-квартирой в Минске. Образована в
            1996 году. Основные рейсовые и чартерные международные полёты осуществляет из Национального аэропорта Минск.
            Полное наименование — Открытое акционерное общество «Авиакомпания «Белавиа».</h5>
        Более подробно вы можете ознакомиться здесь -
<button class="btn btn-success"><a href="{% url 'history' %}">История</a></button><br><br><br>
       <h5> ОАО «Авиакомпания «Белавиа»<br>
Генеральный директор:<br>
Чергинец Игорь Николаевич<br>

Почтовый адрес:<br>
Республика Беларусь, 220004, г.Минск, ул. Немига, 14А</h5>
    </main>
    {% block content %}{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% block extra_js %}{% endblock %}

</body>
</html>

venv13/belavia/accounts/templates/accounts/register.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/demo.css' %}">
<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
<link rel="stylesheet" href="{% static 'css/kaiadmin.css' %}">
<link rel="stylesheet" href="{% static 'css/plugins.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Регистрация{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        body {
            background-color: #77bcf1;

        }

        .container {
            text-align: center;
            border: 2px solid black;
            border-radius: 20px;
            background: #fff;
            margin: 20px auto;
            max-width: 1200px;
            padding: 20px;
            box-shadow: 10px 10px 10px black;
        }
        .post img {
            max-width: 100%;
            border-radius: 10px;
        }
    </style>
    {% block extra_head %}{% endblock %}

</head>
<body>
<div class="container">

<!<h1>Регистрация</h1>

<form class="form-group" method="POST">
    {% csrf_token %}
<!--{    {{ form.as_p }}    }-->

    <label for="id_username">Username</label>
    <input
        type="text"
        class="form-control"
        name="username"
        id="id_username"
        placeholder="Enter username"
        required
        maxlength="150"
    />
    <label for="id_email">Email Address</label>
    <input
        type="email"
        class="form-control"
        name="email"
        id="id_email"
        placeholder="Enter Email"
    />
    <label for="id_password1">Password</label>
    <input
        type="password"
        class="form-control"
        name="password1"
        id="id_password1"
        placeholder="Password"
        required
    />
    <ul>
       <li>Your password can’t be too similar to your other personal information.</li>
        <li>Your password must contain at least 8 characters.</li>
        <li>Your password can’t be a commonly used password.</li>
        <li>Your password can’t be entirely numeric.</li>
    </ul>
    {{ errors }}
    <label for="id_password2">Confirm Password</label>
    <input
        type="password"
        class="form-control"
        name="password2"
        id="id_password2"
        placeholder="Password"
        required
    /><br>
    <button type="submit" class="btn btn-success">Зарегистрироваться</button>
    <p>или</p>
    <button class="btn btn-warning"><a href="{% url 'login' %}">Войти</a></button>
</form>

    {% block content %}{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% block extra_js %}{% endblock %}

</body>
</html>

venv13/belavia/flights/templates/flights/book.html
<h2>Бронирование рейса {{ flight }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Забронировать</button>
</form>

venv13/belavia/flights/templates/flights/confirmatiom.html
<h2>Бронирование рейса {{ flight }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Забронировать</button>
</form>